// ---------------------------------------------------------------------
// Everything in this file is meant to be edited without touching app.js
// or admin.js. See study/README.md § "Changing the intro text" and
// § "Supabase setup" for the full walkthrough.
// ---------------------------------------------------------------------
window.STUDY_CONFIG = {
  // Project: pajxillufzoerhcgtnik. The publishable key is meant to be
  // public — it can only reach the Edge Functions below, nothing else
  // (see study/README.md, "Threat model"). Never put the secret key here.
  SUPABASE_URL: "https://pajxillufzoerhcgtnik.supabase.co",
  SUPABASE_ANON_KEY: "sb_publishable_oJJe_5xKVrDln4YkbvhcOQ_KUhSy8FV",
};

window.STUDY_CONTENT = {
  page_title: "DTM diffusion-model evaluation study",

  // Shown at the top of the intro page. Draft copy — rewrite freely,
  // nothing else on the page depends on the wording.
  heading: "Can you tell a generated terrain image from a real one?",

  // Each entry becomes one paragraph on the intro page, in order.
  // Feel free to add, remove, or rewrite these — nothing else on the
  // page depends on how many there are.
  intro_paragraphs: [
    "We're testing a diffusion model that generates and inpaints " +
      "digital terrain model (DTM) imagery, across four different " +
      "checkpoints of the model. This study asks a simple question: can " +
      "people tell which images are real and which were generated?",
    "You will see a series of images. Some are real, and some were " +
      "generated by the model. For each one, your task is to decide " +
      "whether it is real or AI-generated — you won't be told which " +
      "afterward.",
    "There are 48 images in total, shown 8 at a time. For each one, " +
      "choose “Real,” “AI-generated,” or “Not sure” if you genuinely " +
      "cannot decide. There are no right or wrong answers from your " +
      "side — just make your best judgment based on the image alone.",
    "You can close this page at any point and come back later using the " +
      "resume code you'll be shown after starting — your progress is " +
      "saved after every answer.",
  ],

  // Two labeled examples on the intro page, NOT part of the 48 trials.
  // Replace these two files under study/images/examples/ and update the
  // paths here if you rename them.
  example_real: {
    src: "images/examples/real-example.png",
    caption: "Example — real image",
  },
  example_ai: {
    src: "images/examples/ai-example.png",
    caption: "Example — AI-generated image",
  },

  start_button: "Start experiment",

  completion_heading: "Thank you",
  completion_body:
    "That's the full set — thank you for taking part. Your answers have " +
    "been recorded.",
};
